stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    outs:
    - data/interim
  Feature_engineering:
    cmd: python src/Feature_engineering.py
    deps:
    - src/Feature_engineering.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - src/model_building.py
    params:
    - model_building.n_estimators
    - model_building.random_state
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.scale_pos_weight
    - model_building.subsample
    - model_building.colsample_bytree

    outs:
    - models/xgb_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps: 
    - src/model_evaluation.py
    params:
    - model_evaluation.threshold
    metrics:
    - reports/metrics.json