data_ingestion:
  test_size: 0.20

model_building:
  learning_rate: 0.05
  max_depth: 3
  n_estimators: 100
  scale_pos_weight: 2.0
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42

model_evaluation:
  threshold: 0.55